name: Feature
description: File a Feature
title: 'Feature'
labels: ['💫 Feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: A user story is an informal, general explanation of a software feature written from the perspective of the end user. Its purpose is to articulate how a software feature will provide value to the customer
      placeholder: Tell us what is need it
      value: 'As a [persona], I [want to], [so that]'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us what is need it
      placeholder: Tell us what is need it
      value: 'A new service'
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Write any dependencies (if any)
      placeholder: Write any dependencies (if any)
      value: 'A new service'
    validations:
      required: false
