name: FEWD production deployment
run-name: ${{ github.actor }} is deploying to FEWD production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_FEWD_ID }}
on:
  push:
    tags:
      - 'FEWD*'
    paths:
      - .github/workflows/deploy-fewd-production.yml
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        # TODO: add linters and tests

      - name: Build project artifacts for production
        run: pnpm nx run fewd:build:production

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
