name: FEWD preview deployment
run-name: ${{ github.actor }} is deploying to FEWD preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_FEWD_ID }}
on:
  push:
    branches-ignore:
      - main
    paths:
      - apps/fewd/**
      - .github/workflows/deploy-fewd-next.yml
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install pnpm
        shell: bash
        id: pnpm-install
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        working-directory: .
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        shell: bash
        run: pnpm install
        working-directory: ${{ inputs.working-directory }}

      - name: Install dependencies
        run: pnpm install

      - name: Build project artifacts for preview
        run: pnpm nx run fewd:build:production

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build project artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to Vercel
        run: |
          vercel --cwd ./dist/apps/fewd/.next --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
