name: Deploy FEWD ES 🇪🇸
on:
  push:
    tags:
      - 'ES-FEWD*'
jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node version 📦
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/hydrogen'
          check-latest: true

      - name: Install and Build 🔧
        run: |
          yarn
          yarn lerna run --scope '@shared/**' build
          yarn lerna bootstrap
          yarn workspace @websites/fewd-es build

      - name: Deploy 🚀
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./@websites/fewd-es/build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_FEWD_ES_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
